/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif
PB_BIND(Attribute, Attribute, AUTO)
PB_BIND(Operator, Operator, AUTO)
PB_BIND(Comparator, Comparator, AUTO)
PB_BIND(Filter, Filter, 2)
PB_BIND(Level, Level, 2)
PB_BIND(Query_tree, Query_tree, 4)
PB_BIND(Return_code, Return_code, AUTO)
PB_BIND(Entity, Entity, AUTO)
PB_BIND(Tuple, Tuple, AUTO)
PB_BIND(Collection, Collection, 2)



